### PR TITLE
Housekeeping - nothing to see here, move along

### PR DESCRIPTION
**Pull request by mati865**
1. `std::env::home_dir()` was lying about it's functionality: https://github.com/rust-lang/rust/pull/51656
2. As always: new features/bugs, bug fixes, performance improvements. It would be boring but `regex` gained ability to detect and use SIMD on supported machines: https://github.com/rust-lang/regex/commit/e455d53108495579baa187258794a4eae6ddf8b4
Before:
```
 elfx86exts target/release/cargo-install-update 
MODE64 (call)
CMOV (cmovb)
SSE1 (movups)
SSE2 (movdqu)
```
After:
```
 elfx86exts target/release/cargo-install-update
MODE64 (call)
CMOV (cmovb)
SSE1 (movups)
SSE2 (movdqu)
AVX (vxorps)
AVX2 (vpcmpeqd)
SSSE3 (pshufb)
```
3. Clippy wants to help saving those miliseconds
4. Rustfmt now sorts lines which begin with `use` keyword, there is option (disabled by default) to do the same for `extern crate`

I can squash commits if you want.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -59,7 +59,7 @@ fn actual_main() -> Result<(), i32> {
         if !search_res.success() {
             return Err(search_res.code().unwrap_or(-1));
         }
-        println!("");
```
Comment (nabijaczleweli) [inline src/main.rs]: I'm pretty sure this code pre-dates zero-arg `writeln!()`s :Р
Good catch 👍

File: src/ops/mod.rs [hunk 2]
```diff
@@ -340,7 +340,7 @@ impl GitRepoPackage {
             GitRepoPackage {
                 name: c.get(1).unwrap().as_str().to_string(),
                 url: url.into_string(),
-                branch: branch,
+                branch,
```
Comment (nabijaczleweli) [inline src/ops/mod.rs]: I'd actually rather this stay explicit, as it's more aesthetically pleasing, if you please.

File: src/options.rs [hunk 3]
```diff
@@ -225,7 +225,7 @@ fn cargo_dir() -> (String, PathBuf) {
     }
 }
 
-fn existing_dir_validator(label: &str, s: String) -> Result<(), String> {
+fn existing_dir_validator(label: &str, s: &str) -> Result<(), String> {
     fs::canonicalize(&s).map(|_| ()).map_err(|_| format!("{} directory \"{}\" not found", label, s))
```
Comment (nabijaczleweli) [inline src/options.rs]: There's little difference here though, innit, seeing as the string will've gotten `drop()`ped by the end of the caller's line anyway, but good idiomaticity catch 👍 

(Although, does it work with `fs::canonicalise(s)` here? Seems superiour, innit?)

File: src/main-config.rs [hunk 4]
```diff
@@ -1,10 +1,9 @@
 extern crate cargo_update;
 extern crate tabwriter;
 
-use std::io::{Write, stdout};
-use tabwriter::TabWriter;
+use std::io::{stdout, Write};
 use std::process::exit;
```
Comment (nabijaczleweli) [inline src/main-config.rs]: I'd actually rather this commit dropped, consider the width-priority ordering superiour.

Comment (mati865) [reply src/main-config.rs]: Fine, I'll disable `use` sorting in `rustfmt` config.

File: src/options.rs (hunk 3 above)
Comment (mati865) [reply src/options.rs]: I don't remember if I tried `fs::canonicalise(s)` but yeah looks like it should work.

File: src/ops/mod.rs (hunk 2 above)
Comment (mati865) [reply src/ops/mod.rs]: I'll revert this change and disable the lint.

**Comment by mati865** [comment]
> I'd some, mainly stylistic, nitpicks, (would feel silly to immediately revert an entire commit at merge, when I put my dumb pedantry in :Р).

That's the point of the reviews 😉 
I'll address it on the Monday probably.

Maybe instead of blindly bumping minimal versions it'd better to add CI checking whether the crates in said versions are buildable https://github.com/rust-lang/cargo/issues/5657?

**Comment by nabijaczleweli** [comment]
I'm not sure if I'm extremely dumb (yes), extremely tired (hardly), or if the way the feature's explained just doesn't click for me (probably) but I somehow don't *get* what it does?

**Comment by mati865** [comment]
Versions declared in `Cargo.toml` are in fact "minimal supported versions". Cargo will automatically use latest compatible version, consider this example:
```toml
[dependencies]
foo = "1.0"
```
You are declaring this crate will work with versions: 1.0 >= `foo` < 2.0.
It's not always possible to use latests versions like Cargo does by default so we have two hypothetical environments:

1. Cargo uses latest `foo = "1.1"`, everything works fine.
2. Cargo uses older but declared to work `foo = "1.0"`, everything works fine.

Then you start using `foo::x` without noticing it was added in `foo = "1.1"` and `Cargo.toml` still points to `foo = "1.0"`:

1. Cargo uses latest `foo = "1.1"`, everything works fine.
2. Cargo uses older but declared to work `foo = "1.0"` and user gets the compilation error.

There is ongoing effort to mitigate it by adding CI job with `-Z minimal-versions` to make sure we are not lying about supported dependencies versions. Another less nice solution is to always declare latest versions, "if we support only the latest version we cannot be lying about earlier versions".

**Comment by mati865** [comment]
Updated `libgit2` should fix https://github.com/nabijaczleweli/cargo-update/issues/92

**Comment by nabijaczleweli** [comment]
v1.6.2
